/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "PAPI",
            "endpoint": "https://qwrd6pmyxe.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        },
        {
            "name": "testApi",
            "endpoint": "https://xvnixaajpl.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://y6gndbbdznglfkyucenlghkt7i.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xftat6srwfbrjm6o7u7xeild3i"
};


export default awsmobile;
